// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'annotation-action-explain'
  | 'annotation-action-note'
  | 'annotation-action-summarize'
  | 'chat-input-placeholder'
  | 'chat-panel-header'
  | 'chat-panel-sidenav'
  | 'copy'
  | 'done'
  | 'error-api'
  | 'error-note-save'
  | 'insert-note'
  | 'open-settings'
  | 'pref-api-endpoint'
  | 'pref-api-key'
  | 'pref-help'
  | 'pref-model'
  | 'pref-provider'
  | 'pref-save-key'
  | 'pref-target-language'
  | 'pref-temperature'
  | 'pref-title'
  | 'prefs-title'
  | 'smart-action-explain'
  | 'smart-action-note'
  | 'smart-action-summarize'
  | 'smart-action-translate'
  | 'startup-begin'
  | 'startup-finish'
  | 'thinking';
