// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "openai.model": string;
      "anthropic.model": string;
      "gemini.model": string;
      "custom.model": string;
      "custom.endpoint": string;
      "temperature": string;
      "targetLanguage": string;
      "maxTokens": number;
      "apiEndpoint": string;
      "apiKey": string;
      "model": string;
    };
  }
}
